---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy


# ---

# - name: "configuration play." 
#   hosts: web
#   user: ubuntu
#   gather_facts: false
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_host_key_checking: false
#     - ansible_stdout_callback: yaml
#   # pre_tasks:
#   #     - name: "wait until target is 600 seconds"
#   #       wait_for_connection:
#   #         timeout: 600
#   #     - name: "install python for Ansible."
#   #       become: true
#   #       raw: test -e /usr/bin/python3 || yum -y install python
#   #       changed_when: false
